#ifndef link_appvar_include_file
#define link_appvar_include_file

#ifdef __cplusplus
extern "C" {
#endif

#define link_palette_offset 0
#define link_walk_down_1_width 18
#define link_walk_down_1_height 25
#define link_link_link_walk_down_1_index 0
#define link_walk_down_1 ((gfx_sprite_t*)link_appvar[0])
#define link_walk_down_2_width 18
#define link_walk_down_2_height 23
#define link_link_link_walk_down_2_index 1
#define link_walk_down_2 ((gfx_sprite_t*)link_appvar[1])
#define link_walk_down_3_width 18
#define link_walk_down_3_height 25
#define link_link_link_walk_down_3_index 2
#define link_walk_down_3 ((gfx_sprite_t*)link_appvar[2])
#define link_walk_down_4_width 18
#define link_walk_down_4_height 26
#define link_link_link_walk_down_4_index 3
#define link_walk_down_4 ((gfx_sprite_t*)link_appvar[3])
#define link_walk_down_5_width 18
#define link_walk_down_5_height 27
#define link_link_link_walk_down_5_index 4
#define link_walk_down_5 ((gfx_sprite_t*)link_appvar[4])
#define link_walk_down_6_width 18
#define link_walk_down_6_height 25
#define link_link_link_walk_down_6_index 5
#define link_walk_down_6 ((gfx_sprite_t*)link_appvar[5])
#define link_walk_down_7_width 18
#define link_walk_down_7_height 23
#define link_link_link_walk_down_7_index 6
#define link_walk_down_7 ((gfx_sprite_t*)link_appvar[6])
#define link_walk_down_8_width 18
#define link_walk_down_8_height 25
#define link_link_link_walk_down_8_index 7
#define link_walk_down_8 ((gfx_sprite_t*)link_appvar[7])
#define link_walk_down_9_width 18
#define link_walk_down_9_height 26
#define link_link_link_walk_down_9_index 8
#define link_walk_down_9 ((gfx_sprite_t*)link_appvar[8])
#define link_walk_down_10_width 18
#define link_walk_down_10_height 27
#define link_link_link_walk_down_10_index 9
#define link_walk_down_10 ((gfx_sprite_t*)link_appvar[9])
#define link_walk_side_1_width 20
#define link_walk_side_1_height 26
#define link_link_link_walk_side_1_index 10
#define link_walk_side_1 ((gfx_sprite_t*)link_appvar[10])
#define link_walk_side_2_width 20
#define link_walk_side_2_height 24
#define link_link_link_walk_side_2_index 11
#define link_walk_side_2 ((gfx_sprite_t*)link_appvar[11])
#define link_walk_side_3_width 22
#define link_walk_side_3_height 23
#define link_link_link_walk_side_3_index 12
#define link_walk_side_3 ((gfx_sprite_t*)link_appvar[12])
#define link_walk_side_4_width 21
#define link_walk_side_4_height 25
#define link_link_link_walk_side_4_index 13
#define link_walk_side_4 ((gfx_sprite_t*)link_appvar[13])
#define link_walk_side_5_width 20
#define link_walk_side_5_height 26
#define link_link_link_walk_side_5_index 14
#define link_walk_side_5 ((gfx_sprite_t*)link_appvar[14])
#define link_walk_side_6_width 20
#define link_walk_side_6_height 26
#define link_link_link_walk_side_6_index 15
#define link_walk_side_6 ((gfx_sprite_t*)link_appvar[15])
#define link_walk_side_7_width 19
#define link_walk_side_7_height 25
#define link_link_link_walk_side_7_index 16
#define link_walk_side_7 ((gfx_sprite_t*)link_appvar[16])
#define link_walk_side_8_width 21
#define link_walk_side_8_height 24
#define link_link_link_walk_side_8_index 17
#define link_walk_side_8 ((gfx_sprite_t*)link_appvar[17])
#define link_walk_side_9_width 20
#define link_walk_side_9_height 25
#define link_link_link_walk_side_9_index 18
#define link_walk_side_9 ((gfx_sprite_t*)link_appvar[18])
#define link_walk_side_10_width 20
#define link_walk_side_10_height 26
#define link_link_link_walk_side_10_index 19
#define link_walk_side_10 ((gfx_sprite_t*)link_appvar[19])
#define link_walk_up_1_width 18
#define link_walk_up_1_height 25
#define link_link_link_walk_up_1_index 20
#define link_walk_up_1 ((gfx_sprite_t*)link_appvar[20])
#define link_walk_up_2_width 18
#define link_walk_up_2_height 24
#define link_link_link_walk_up_2_index 21
#define link_walk_up_2 ((gfx_sprite_t*)link_appvar[21])
#define link_walk_up_3_width 18
#define link_walk_up_3_height 25
#define link_link_link_walk_up_3_index 22
#define link_walk_up_3 ((gfx_sprite_t*)link_appvar[22])
#define link_walk_up_4_width 18
#define link_walk_up_4_height 28
#define link_link_link_walk_up_4_index 23
#define link_walk_up_4 ((gfx_sprite_t*)link_appvar[23])
#define link_walk_up_5_width 18
#define link_walk_up_5_height 27
#define link_link_link_walk_up_5_index 24
#define link_walk_up_5 ((gfx_sprite_t*)link_appvar[24])
#define link_walk_up_6_width 18
#define link_walk_up_6_height 25
#define link_link_link_walk_up_6_index 25
#define link_walk_up_6 ((gfx_sprite_t*)link_appvar[25])
#define link_walk_up_7_width 18
#define link_walk_up_7_height 24
#define link_link_link_walk_up_7_index 26
#define link_walk_up_7 ((gfx_sprite_t*)link_appvar[26])
#define link_walk_up_8_width 18
#define link_walk_up_8_height 25
#define link_link_link_walk_up_8_index 27
#define link_walk_up_8 ((gfx_sprite_t*)link_appvar[27])
#define link_walk_up_9_width 18
#define link_walk_up_9_height 28
#define link_link_link_walk_up_9_index 28
#define link_walk_up_9 ((gfx_sprite_t*)link_appvar[28])
#define link_walk_up_10_width 18
#define link_walk_up_10_height 27
#define link_link_link_walk_up_10_index 29
#define link_walk_up_10 ((gfx_sprite_t*)link_appvar[29])
#define link_idle_down_width 18
#define link_idle_down_height 25
#define link_link_link_idle_down_index 30
#define link_idle_down ((gfx_sprite_t*)link_appvar[30])
#define link_idle_side_width 19
#define link_idle_side_height 25
#define link_link_link_idle_side_index 31
#define link_idle_side ((gfx_sprite_t*)link_appvar[31])
#define link_idle_up_width 18
#define link_idle_up_height 24
#define link_link_link_idle_up_index 32
#define link_idle_up ((gfx_sprite_t*)link_appvar[32])
#define link_entries_num 33
extern unsigned char *link_appvar[33];
unsigned char link_init(void);

#ifdef __cplusplus
}
#endif

#endif
